// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileInfo.proto

package com.buaa.cfs.protobufer;

public final class CfsProto {
  private CfsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BlockInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fileId = 1;
    /**
     * <code>required string fileId = 1;</code>
     */
    boolean hasFileId();
    /**
     * <code>required string fileId = 1;</code>
     */
    String getFileId();
    /**
     * <code>required string fileId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    // required string bolckId = 2;
    /**
     * <code>required string bolckId = 2;</code>
     */
    boolean hasBolckId();
    /**
     * <code>required string bolckId = 2;</code>
     */
    String getBolckId();
    /**
     * <code>required string bolckId = 2;</code>
     */
    com.google.protobuf.ByteString
        getBolckIdBytes();

    // required int64 blockSize = 3;
    /**
     * <code>required int64 blockSize = 3;</code>
     */
    boolean hasBlockSize();
    /**
     * <code>required int64 blockSize = 3;</code>
     */
    long getBlockSize();

    // required string crc64_value = 4;
    /**
     * <code>required string crc64_value = 4;</code>
     */
    boolean hasCrc64Value();
    /**
     * <code>required string crc64_value = 4;</code>
     */
    String getCrc64Value();
    /**
     * <code>required string crc64_value = 4;</code>
     */
    com.google.protobuf.ByteString
        getCrc64ValueBytes();

    // required bytes value = 5;
    /**
     * <code>required bytes value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 5;</code>
     */
    com.google.protobuf.ByteString getValue();

    // required bool eof = 6;
    /**
     * <code>required bool eof = 6;</code>
     */
    boolean hasEof();
    /**
     * <code>required bool eof = 6;</code>
     */
    boolean getEof();
  }
  /**
   * Protobuf type {@code BlockInfo}
   */
  public static final class BlockInfo extends
      com.google.protobuf.GeneratedMessage
      implements BlockInfoOrBuilder {
    // Use BlockInfo.newBuilder() to construct.
    private BlockInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BlockInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BlockInfo defaultInstance;
    public static BlockInfo getDefaultInstance() {
      return defaultInstance;
    }

    public BlockInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BlockInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bolckId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              blockSize_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              crc64Value_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              value_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              eof_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CfsProto.internal_static_BlockInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CfsProto.internal_static_BlockInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BlockInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<BlockInfo> PARSER =
        new com.google.protobuf.AbstractParser<BlockInfo>() {
      public BlockInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BlockInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private Object fileId_;
    /**
     * <code>required string fileId = 1;</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fileId = 1;</code>
     */
    public String getFileId() {
      Object ref = fileId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string bolckId = 2;
    public static final int BOLCKID_FIELD_NUMBER = 2;
    private Object bolckId_;
    /**
     * <code>required string bolckId = 2;</code>
     */
    public boolean hasBolckId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string bolckId = 2;</code>
     */
    public String getBolckId() {
      Object ref = bolckId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bolckId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bolckId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBolckIdBytes() {
      Object ref = bolckId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bolckId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 blockSize = 3;
    public static final int BLOCKSIZE_FIELD_NUMBER = 3;
    private long blockSize_;
    /**
     * <code>required int64 blockSize = 3;</code>
     */
    public boolean hasBlockSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 blockSize = 3;</code>
     */
    public long getBlockSize() {
      return blockSize_;
    }

    // required string crc64_value = 4;
    public static final int CRC64_VALUE_FIELD_NUMBER = 4;
    private Object crc64Value_;
    /**
     * <code>required string crc64_value = 4;</code>
     */
    public boolean hasCrc64Value() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string crc64_value = 4;</code>
     */
    public String getCrc64Value() {
      Object ref = crc64Value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          crc64Value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string crc64_value = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCrc64ValueBytes() {
      Object ref = crc64Value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        crc64Value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes value = 5;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    // required bool eof = 6;
    public static final int EOF_FIELD_NUMBER = 6;
    private boolean eof_;
    /**
     * <code>required bool eof = 6;</code>
     */
    public boolean hasEof() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool eof = 6;</code>
     */
    public boolean getEof() {
      return eof_;
    }

    private void initFields() {
      fileId_ = "";
      bolckId_ = "";
      blockSize_ = 0L;
      crc64Value_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      eof_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFileId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBolckId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCrc64Value()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEof()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBolckIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, blockSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCrc64ValueBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, eof_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBolckIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, blockSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCrc64ValueBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, eof_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BlockInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BlockInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BlockInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BlockInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BlockInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BlockInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BlockInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BlockInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BlockInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlockInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BlockInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CfsProto.internal_static_BlockInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CfsProto.internal_static_BlockInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BlockInfo.class, Builder.class);
      }

      // Construct using com.buaa.cfs.protobufer.CfsProto.BlockInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bolckId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        blockSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        crc64Value_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        eof_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CfsProto.internal_static_BlockInfo_descriptor;
      }

      public BlockInfo getDefaultInstanceForType() {
        return BlockInfo.getDefaultInstance();
      }

      public BlockInfo build() {
        BlockInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BlockInfo buildPartial() {
        BlockInfo result = new BlockInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bolckId_ = bolckId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.blockSize_ = blockSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.crc64Value_ = crc64Value_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.eof_ = eof_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BlockInfo) {
          return mergeFrom((BlockInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BlockInfo other) {
        if (other == BlockInfo.getDefaultInstance()) return this;
        if (other.hasFileId()) {
          bitField0_ |= 0x00000001;
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasBolckId()) {
          bitField0_ |= 0x00000002;
          bolckId_ = other.bolckId_;
          onChanged();
        }
        if (other.hasBlockSize()) {
          setBlockSize(other.getBlockSize());
        }
        if (other.hasCrc64Value()) {
          bitField0_ |= 0x00000008;
          crc64Value_ = other.crc64Value_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasEof()) {
          setEof(other.getEof());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFileId()) {
          
          return false;
        }
        if (!hasBolckId()) {
          
          return false;
        }
        if (!hasBlockSize()) {
          
          return false;
        }
        if (!hasCrc64Value()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        if (!hasEof()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BlockInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BlockInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fileId = 1;
      private Object fileId_ = "";
      /**
       * <code>required string fileId = 1;</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public String getFileId() {
        Object ref = fileId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder setFileId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }

      // required string bolckId = 2;
      private Object bolckId_ = "";
      /**
       * <code>required string bolckId = 2;</code>
       */
      public boolean hasBolckId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string bolckId = 2;</code>
       */
      public String getBolckId() {
        Object ref = bolckId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bolckId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string bolckId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBolckIdBytes() {
        Object ref = bolckId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bolckId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bolckId = 2;</code>
       */
      public Builder setBolckId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bolckId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bolckId = 2;</code>
       */
      public Builder clearBolckId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bolckId_ = getDefaultInstance().getBolckId();
        onChanged();
        return this;
      }
      /**
       * <code>required string bolckId = 2;</code>
       */
      public Builder setBolckIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bolckId_ = value;
        onChanged();
        return this;
      }

      // required int64 blockSize = 3;
      private long blockSize_ ;
      /**
       * <code>required int64 blockSize = 3;</code>
       */
      public boolean hasBlockSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 blockSize = 3;</code>
       */
      public long getBlockSize() {
        return blockSize_;
      }
      /**
       * <code>required int64 blockSize = 3;</code>
       */
      public Builder setBlockSize(long value) {
        bitField0_ |= 0x00000004;
        blockSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 blockSize = 3;</code>
       */
      public Builder clearBlockSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        blockSize_ = 0L;
        onChanged();
        return this;
      }

      // required string crc64_value = 4;
      private Object crc64Value_ = "";
      /**
       * <code>required string crc64_value = 4;</code>
       */
      public boolean hasCrc64Value() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string crc64_value = 4;</code>
       */
      public String getCrc64Value() {
        Object ref = crc64Value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          crc64Value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string crc64_value = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCrc64ValueBytes() {
        Object ref = crc64Value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          crc64Value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string crc64_value = 4;</code>
       */
      public Builder setCrc64Value(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        crc64Value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string crc64_value = 4;</code>
       */
      public Builder clearCrc64Value() {
        bitField0_ = (bitField0_ & ~0x00000008);
        crc64Value_ = getDefaultInstance().getCrc64Value();
        onChanged();
        return this;
      }
      /**
       * <code>required string crc64_value = 4;</code>
       */
      public Builder setCrc64ValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        crc64Value_ = value;
        onChanged();
        return this;
      }

      // required bytes value = 5;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes value = 5;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 5;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // required bool eof = 6;
      private boolean eof_ ;
      /**
       * <code>required bool eof = 6;</code>
       */
      public boolean hasEof() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool eof = 6;</code>
       */
      public boolean getEof() {
        return eof_;
      }
      /**
       * <code>required bool eof = 6;</code>
       */
      public Builder setEof(boolean value) {
        bitField0_ |= 0x00000020;
        eof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool eof = 6;</code>
       */
      public Builder clearEof() {
        bitField0_ = (bitField0_ & ~0x00000020);
        eof_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BlockInfo)
    }

    static {
      defaultInstance = new BlockInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BlockInfo)
  }

  public interface FileInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fileId = 1;
    /**
     * <code>required string fileId = 1;</code>
     */
    boolean hasFileId();
    /**
     * <code>required string fileId = 1;</code>
     */
    String getFileId();
    /**
     * <code>required string fileId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    // required int64 fileSize = 2;
    /**
     * <code>required int64 fileSize = 2;</code>
     */
    boolean hasFileSize();
    /**
     * <code>required int64 fileSize = 2;</code>
     */
    long getFileSize();

    // required string md5_value = 3;
    /**
     * <code>required string md5_value = 3;</code>
     */
    boolean hasMd5Value();
    /**
     * <code>required string md5_value = 3;</code>
     */
    String getMd5Value();
    /**
     * <code>required string md5_value = 3;</code>
     */
    com.google.protobuf.ByteString
        getMd5ValueBytes();

    // required int32 block_num = 4;
    /**
     * <code>required int32 block_num = 4;</code>
     */
    boolean hasBlockNum();
    /**
     * <code>required int32 block_num = 4;</code>
     */
    int getBlockNum();
  }
  /**
   * Protobuf type {@code FileInfo}
   */
  public static final class FileInfo extends
      com.google.protobuf.GeneratedMessage
      implements FileInfoOrBuilder {
    // Use FileInfo.newBuilder() to construct.
    private FileInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileInfo defaultInstance;
    public static FileInfo getDefaultInstance() {
      return defaultInstance;
    }

    public FileInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fileSize_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              md5Value_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              blockNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CfsProto.internal_static_FileInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CfsProto.internal_static_FileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FileInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<FileInfo> PARSER =
        new com.google.protobuf.AbstractParser<FileInfo>() {
      public FileInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<FileInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string fileId = 1;
    public static final int FILEID_FIELD_NUMBER = 1;
    private Object fileId_;
    /**
     * <code>required string fileId = 1;</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fileId = 1;</code>
     */
    public String getFileId() {
      Object ref = fileId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 fileSize = 2;
    public static final int FILESIZE_FIELD_NUMBER = 2;
    private long fileSize_;
    /**
     * <code>required int64 fileSize = 2;</code>
     */
    public boolean hasFileSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 fileSize = 2;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    // required string md5_value = 3;
    public static final int MD5_VALUE_FIELD_NUMBER = 3;
    private Object md5Value_;
    /**
     * <code>required string md5_value = 3;</code>
     */
    public boolean hasMd5Value() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string md5_value = 3;</code>
     */
    public String getMd5Value() {
      Object ref = md5Value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          md5Value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string md5_value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMd5ValueBytes() {
      Object ref = md5Value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        md5Value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 block_num = 4;
    public static final int BLOCK_NUM_FIELD_NUMBER = 4;
    private int blockNum_;
    /**
     * <code>required int32 block_num = 4;</code>
     */
    public boolean hasBlockNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 block_num = 4;</code>
     */
    public int getBlockNum() {
      return blockNum_;
    }

    private void initFields() {
      fileId_ = "";
      fileSize_ = 0L;
      md5Value_ = "";
      blockNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFileId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMd5Value()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fileSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMd5ValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, blockNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fileSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMd5ValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, blockNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static FileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static FileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static FileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static FileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static FileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(FileInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements FileInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CfsProto.internal_static_FileInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CfsProto.internal_static_FileInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FileInfo.class, Builder.class);
      }

      // Construct using com.buaa.cfs.protobufer.CfsProto.FileInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fileSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        md5Value_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        blockNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CfsProto.internal_static_FileInfo_descriptor;
      }

      public FileInfo getDefaultInstanceForType() {
        return FileInfo.getDefaultInstance();
      }

      public FileInfo build() {
        FileInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public FileInfo buildPartial() {
        FileInfo result = new FileInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileSize_ = fileSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.md5Value_ = md5Value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.blockNum_ = blockNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FileInfo) {
          return mergeFrom((FileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FileInfo other) {
        if (other == FileInfo.getDefaultInstance()) return this;
        if (other.hasFileId()) {
          bitField0_ |= 0x00000001;
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasFileSize()) {
          setFileSize(other.getFileSize());
        }
        if (other.hasMd5Value()) {
          bitField0_ |= 0x00000004;
          md5Value_ = other.md5Value_;
          onChanged();
        }
        if (other.hasBlockNum()) {
          setBlockNum(other.getBlockNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFileId()) {
          
          return false;
        }
        if (!hasFileSize()) {
          
          return false;
        }
        if (!hasMd5Value()) {
          
          return false;
        }
        if (!hasBlockNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FileInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FileInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fileId = 1;
      private Object fileId_ = "";
      /**
       * <code>required string fileId = 1;</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public String getFileId() {
        Object ref = fileId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder setFileId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileId = 1;</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileId_ = value;
        onChanged();
        return this;
      }

      // required int64 fileSize = 2;
      private long fileSize_ ;
      /**
       * <code>required int64 fileSize = 2;</code>
       */
      public boolean hasFileSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 fileSize = 2;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>required int64 fileSize = 2;</code>
       */
      public Builder setFileSize(long value) {
        bitField0_ |= 0x00000002;
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fileSize = 2;</code>
       */
      public Builder clearFileSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      // required string md5_value = 3;
      private Object md5Value_ = "";
      /**
       * <code>required string md5_value = 3;</code>
       */
      public boolean hasMd5Value() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string md5_value = 3;</code>
       */
      public String getMd5Value() {
        Object ref = md5Value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          md5Value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string md5_value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMd5ValueBytes() {
        Object ref = md5Value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          md5Value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string md5_value = 3;</code>
       */
      public Builder setMd5Value(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        md5Value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string md5_value = 3;</code>
       */
      public Builder clearMd5Value() {
        bitField0_ = (bitField0_ & ~0x00000004);
        md5Value_ = getDefaultInstance().getMd5Value();
        onChanged();
        return this;
      }
      /**
       * <code>required string md5_value = 3;</code>
       */
      public Builder setMd5ValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        md5Value_ = value;
        onChanged();
        return this;
      }

      // required int32 block_num = 4;
      private int blockNum_ ;
      /**
       * <code>required int32 block_num = 4;</code>
       */
      public boolean hasBlockNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 block_num = 4;</code>
       */
      public int getBlockNum() {
        return blockNum_;
      }
      /**
       * <code>required int32 block_num = 4;</code>
       */
      public Builder setBlockNum(int value) {
        bitField0_ |= 0x00000008;
        blockNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 block_num = 4;</code>
       */
      public Builder clearBlockNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        blockNum_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FileInfo)
    }

    static {
      defaultInstance = new FileInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FileInfo)
  }

  public interface CfsMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .FileInfo fileInfo = 1;
    /**
     * <code>optional .FileInfo fileInfo = 1;</code>
     */
    boolean hasFileInfo();
    /**
     * <code>optional .FileInfo fileInfo = 1;</code>
     */
    FileInfo getFileInfo();
    /**
     * <code>optional .FileInfo fileInfo = 1;</code>
     */
    FileInfoOrBuilder getFileInfoOrBuilder();

    // optional .BlockInfo blockInfo = 2;
    /**
     * <code>optional .BlockInfo blockInfo = 2;</code>
     */
    boolean hasBlockInfo();
    /**
     * <code>optional .BlockInfo blockInfo = 2;</code>
     */
    BlockInfo getBlockInfo();
    /**
     * <code>optional .BlockInfo blockInfo = 2;</code>
     */
    BlockInfoOrBuilder getBlockInfoOrBuilder();

    // required string id = 3;
    /**
     * <code>required string id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 3;</code>
     */
    String getId();
    /**
     * <code>required string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code CfsMessage}
   */
  public static final class CfsMessage extends
      com.google.protobuf.GeneratedMessage
      implements CfsMessageOrBuilder {
    // Use CfsMessage.newBuilder() to construct.
    private CfsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CfsMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CfsMessage defaultInstance;
    public static CfsMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CfsMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CfsMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              FileInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = fileInfo_.toBuilder();
              }
              fileInfo_ = input.readMessage(FileInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fileInfo_);
                fileInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              BlockInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = blockInfo_.toBuilder();
              }
              blockInfo_ = input.readMessage(BlockInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(blockInfo_);
                blockInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              id_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CfsProto.internal_static_CfsMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CfsProto.internal_static_CfsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CfsMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CfsMessage> PARSER =
        new com.google.protobuf.AbstractParser<CfsMessage>() {
      public CfsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CfsMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CfsMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .FileInfo fileInfo = 1;
    public static final int FILEINFO_FIELD_NUMBER = 1;
    private FileInfo fileInfo_;
    /**
     * <code>optional .FileInfo fileInfo = 1;</code>
     */
    public boolean hasFileInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .FileInfo fileInfo = 1;</code>
     */
    public FileInfo getFileInfo() {
      return fileInfo_;
    }
    /**
     * <code>optional .FileInfo fileInfo = 1;</code>
     */
    public FileInfoOrBuilder getFileInfoOrBuilder() {
      return fileInfo_;
    }

    // optional .BlockInfo blockInfo = 2;
    public static final int BLOCKINFO_FIELD_NUMBER = 2;
    private BlockInfo blockInfo_;
    /**
     * <code>optional .BlockInfo blockInfo = 2;</code>
     */
    public boolean hasBlockInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .BlockInfo blockInfo = 2;</code>
     */
    public BlockInfo getBlockInfo() {
      return blockInfo_;
    }
    /**
     * <code>optional .BlockInfo blockInfo = 2;</code>
     */
    public BlockInfoOrBuilder getBlockInfoOrBuilder() {
      return blockInfo_;
    }

    // required string id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private Object id_;
    /**
     * <code>required string id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string id = 3;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fileInfo_ = FileInfo.getDefaultInstance();
      blockInfo_ = BlockInfo.getDefaultInstance();
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFileInfo()) {
        if (!getFileInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBlockInfo()) {
        if (!getBlockInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, fileInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, blockInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fileInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, blockInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CfsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CfsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CfsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CfsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CfsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CfsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CfsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CfsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CfsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CfsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CfsMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CfsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CfsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CfsProto.internal_static_CfsMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CfsProto.internal_static_CfsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CfsMessage.class, Builder.class);
      }

      // Construct using com.buaa.cfs.protobufer.CfsProto.CfsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFileInfoFieldBuilder();
          getBlockInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (fileInfoBuilder_ == null) {
          fileInfo_ = FileInfo.getDefaultInstance();
        } else {
          fileInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (blockInfoBuilder_ == null) {
          blockInfo_ = BlockInfo.getDefaultInstance();
        } else {
          blockInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CfsProto.internal_static_CfsMessage_descriptor;
      }

      public CfsMessage getDefaultInstanceForType() {
        return CfsMessage.getDefaultInstance();
      }

      public CfsMessage build() {
        CfsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CfsMessage buildPartial() {
        CfsMessage result = new CfsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (fileInfoBuilder_ == null) {
          result.fileInfo_ = fileInfo_;
        } else {
          result.fileInfo_ = fileInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (blockInfoBuilder_ == null) {
          result.blockInfo_ = blockInfo_;
        } else {
          result.blockInfo_ = blockInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CfsMessage) {
          return mergeFrom((CfsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CfsMessage other) {
        if (other == CfsMessage.getDefaultInstance()) return this;
        if (other.hasFileInfo()) {
          mergeFileInfo(other.getFileInfo());
        }
        if (other.hasBlockInfo()) {
          mergeBlockInfo(other.getBlockInfo());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000004;
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasFileInfo()) {
          if (!getFileInfo().isInitialized()) {
            
            return false;
          }
        }
        if (hasBlockInfo()) {
          if (!getBlockInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CfsMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CfsMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .FileInfo fileInfo = 1;
      private FileInfo fileInfo_ = FileInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          FileInfo, FileInfo.Builder, FileInfoOrBuilder> fileInfoBuilder_;
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public boolean hasFileInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public FileInfo getFileInfo() {
        if (fileInfoBuilder_ == null) {
          return fileInfo_;
        } else {
          return fileInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public Builder setFileInfo(FileInfo value) {
        if (fileInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileInfo_ = value;
          onChanged();
        } else {
          fileInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public Builder setFileInfo(
          FileInfo.Builder builderForValue) {
        if (fileInfoBuilder_ == null) {
          fileInfo_ = builderForValue.build();
          onChanged();
        } else {
          fileInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public Builder mergeFileInfo(FileInfo value) {
        if (fileInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              fileInfo_ != FileInfo.getDefaultInstance()) {
            fileInfo_ =
              FileInfo.newBuilder(fileInfo_).mergeFrom(value).buildPartial();
          } else {
            fileInfo_ = value;
          }
          onChanged();
        } else {
          fileInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public Builder clearFileInfo() {
        if (fileInfoBuilder_ == null) {
          fileInfo_ = FileInfo.getDefaultInstance();
          onChanged();
        } else {
          fileInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public FileInfo.Builder getFileInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFileInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      public FileInfoOrBuilder getFileInfoOrBuilder() {
        if (fileInfoBuilder_ != null) {
          return fileInfoBuilder_.getMessageOrBuilder();
        } else {
          return fileInfo_;
        }
      }
      /**
       * <code>optional .FileInfo fileInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          FileInfo, FileInfo.Builder, FileInfoOrBuilder>
          getFileInfoFieldBuilder() {
        if (fileInfoBuilder_ == null) {
          fileInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              FileInfo, FileInfo.Builder, FileInfoOrBuilder>(
                  fileInfo_,
                  getParentForChildren(),
                  isClean());
          fileInfo_ = null;
        }
        return fileInfoBuilder_;
      }

      // optional .BlockInfo blockInfo = 2;
      private BlockInfo blockInfo_ = BlockInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BlockInfo, BlockInfo.Builder, BlockInfoOrBuilder> blockInfoBuilder_;
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public boolean hasBlockInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public BlockInfo getBlockInfo() {
        if (blockInfoBuilder_ == null) {
          return blockInfo_;
        } else {
          return blockInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public Builder setBlockInfo(BlockInfo value) {
        if (blockInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blockInfo_ = value;
          onChanged();
        } else {
          blockInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public Builder setBlockInfo(
          BlockInfo.Builder builderForValue) {
        if (blockInfoBuilder_ == null) {
          blockInfo_ = builderForValue.build();
          onChanged();
        } else {
          blockInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public Builder mergeBlockInfo(BlockInfo value) {
        if (blockInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              blockInfo_ != BlockInfo.getDefaultInstance()) {
            blockInfo_ =
              BlockInfo.newBuilder(blockInfo_).mergeFrom(value).buildPartial();
          } else {
            blockInfo_ = value;
          }
          onChanged();
        } else {
          blockInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public Builder clearBlockInfo() {
        if (blockInfoBuilder_ == null) {
          blockInfo_ = BlockInfo.getDefaultInstance();
          onChanged();
        } else {
          blockInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public BlockInfo.Builder getBlockInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBlockInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      public BlockInfoOrBuilder getBlockInfoOrBuilder() {
        if (blockInfoBuilder_ != null) {
          return blockInfoBuilder_.getMessageOrBuilder();
        } else {
          return blockInfo_;
        }
      }
      /**
       * <code>optional .BlockInfo blockInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BlockInfo, BlockInfo.Builder, BlockInfoOrBuilder>
          getBlockInfoFieldBuilder() {
        if (blockInfoBuilder_ == null) {
          blockInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BlockInfo, BlockInfo.Builder, BlockInfoOrBuilder>(
                  blockInfo_,
                  getParentForChildren(),
                  isClean());
          blockInfo_ = null;
        }
        return blockInfoBuilder_;
      }

      // required string id = 3;
      private Object id_ = "";
      /**
       * <code>required string id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string id = 3;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CfsMessage)
    }

    static {
      defaultInstance = new CfsMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CfsMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BlockInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BlockInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FileInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CfsMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CfsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016FileInfo.proto\"p\n\tBlockInfo\022\016\n\006fileId\030" +
      "\001 \002(\t\022\017\n\007bolckId\030\002 \002(\t\022\021\n\tblockSize\030\003 \002(" +
      "\003\022\023\n\013crc64_value\030\004 \002(\t\022\r\n\005value\030\005 \002(\014\022\013\n" +
      "\003eof\030\006 \002(\010\"R\n\010FileInfo\022\016\n\006fileId\030\001 \002(\t\022\020" +
      "\n\010fileSize\030\002 \002(\003\022\021\n\tmd5_value\030\003 \002(\t\022\021\n\tb" +
      "lock_num\030\004 \002(\005\"T\n\nCfsMessage\022\033\n\010fileInfo" +
      "\030\001 \001(\0132\t.FileInfo\022\035\n\tblockInfo\030\002 \001(\0132\n.B" +
      "lockInfo\022\n\n\002id\030\003 \002(\tB#\n\027com.buaa.cfs.pro" +
      "tobuferB\010CfsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BlockInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BlockInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BlockInfo_descriptor,
              new String[] { "FileId", "BolckId", "BlockSize", "Crc64Value", "Value", "Eof", });
          internal_static_FileInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_FileInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FileInfo_descriptor,
              new String[] { "FileId", "FileSize", "Md5Value", "BlockNum", });
          internal_static_CfsMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CfsMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CfsMessage_descriptor,
              new String[] { "FileInfo", "BlockInfo", "Id", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
